language: ruby
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - bundle exec rake test_app
script:
  - bundle exec rspec spec
rvm:
  - 1.9.3
branches:
  only:
    - 2-1-to-2-0